import React from "react";

export default class termsofservice extends React.Component{
    render(){
        return(
            <div className="container ">
               
                                <h2 className="blue-text">Terms and Conditions</h2>
                <p>Last updated: June 29, 2020</p>
                <p>Please read these terms and conditions carefully before using Our Service.</p>
                <h5>TERMS AND CONDITIONS FOR HIRING THE VEHICLE.</h5>
                <p>I AGREE TO RENT FROM SNAPWHEELS A MOTORCYCLE AND AGREE TO THE TERMS BELOW.</p>
                <br />
                <p>MY REPRESENTATIONS: : I REPRESENT TO SNAPWHEELS THAT (A) I AM AT LEAST 18 YEARS OF AGE AND IN SOUND MEDICAL CONDITION, (B) I POSSESS A VALID DRIVERS LICENSE THAT QUALIFIES ME TO OPERATE A MOTORCYCLE IN MY PERMANENT STATE OR COUNTRY OF RESIDENCE, (C) I WILL NOT OPERATE THE MOTORCYCLE UNLESS WEARING A DOT CERTIFIED HELMET, AND (D) I AM NOT UNDER THE INFLUENCE OF AN ALCOHOLIC BEVERAGE OR CONTROLLED SUBSTANCE INCLUDING PRESCRIPTION OR NONPRESCRIPTION MEDICATION WHICH COULD IMPAIR MY ABILITY TO OPERATE THE MOTORCYCLE SAFELY.</p>
                <br />
                <p>OWNERSHIP AND USE: SNAPWHEELS IS THE OWNER OF THE MOTORCYCLE, AND NEITHER I NOR ANYONE ELSE WILL ACQUIRE ANY INTEREST IN THE MOTORCYCLE BY REASON OF THIS AGREEMENT.
                     I WILL NOT OPERATE OR TRANSPORT THE MOTORCYCLE OUTSIDE INDIA. I WILL COMPLY WITH ALL LAWS, ORDINANCES AND GOVERNMENT REGULATIONS RELATING TO USE AND OPERATION OF THE MOTORCYCLE.
                      IT IS MY RESPONSIBILITY TO KNOW THE LAWS, ORDINANCES, AND GOVERNMENT REGULATIONS. I WILL CHECK THE MOTORCYCLE ENGINE OIL LEVEL EACH TIME I REFUEL.
                       I WILL REPORT ANY MECHANICAL FAILURES TO SNAPWHEELS IMMEDIATELY. I WILL NOT SERVICE OR REPAIR THE MOTORCYCLE, OR REPLACE ANY PART OR ACCESSORY WITHOUT SNAPWHEELS PRIOR APPROVAL, 
                       OR SUCH ACTIONS ARE AT MY RISK AND EXPENSE. I WILL KEEP THE MOTORCYCLE LOCKED WHILE UNATTENDED. IN CASE OF AN ACCIDENT INVOLVING THE MOTORCYCLE I WILL CALL AND NOTIFY THE POLICE AND SNAPWHEELS IMMEDIATELY. 
                       IF I AM INVOLVED IN AN ACCIDENT I UNDERSTAND THE MOTORCYCLE WILL NOT BE REPLACED, AND THIS AGREEMENT WILL AUTOMATICALLY BE TERMINATED WITHOUT REFUND.
                     IN ADDITION I WILL REPORT ANY SERVICE PROBLEMS TO SNAPWHEELS IMMEDIATELY AND WILL NOT OPERATE THE VEHICLE WITH ANY WARNING LIGHTS ON. 
                     I WILL STOP IMMEDIATELY IN THE EVENT OF A TEMPORATURE OR OIL INDICATOR.</p>
                     <br />
                <p>DOCUMENTS REQUIRED: I SHALL FURNISH A VALID DRIVING LICENSE AT THE TIME OF PICKING UP THE VEHICLE. IN ADDITION, I SHALL SUBMIT AN ORIGINAL ID PROOF (PASSPORT, VOTERS ID OR ADHAAR CARD) AND DISPLAY PRESENT ADDRESS PROOF (COLLEGE ID / EMPLOYMENT PROOF (EG. COMPANY ID CARD, OFFER LETTER, VISITING CARD, CORPORATE EMAIL CONFIRMATION E.T.C) / PRESENT ADDRESS PROOF (ELECTRICITY BILL, MOBILE BILL OR BROADBAND BILL) / DIGILOCKER ADDRESS VERIFICATION) AT THE TIME OF PICKING UP THE VEHICLE. I am aware that only passport will be considered for submission of original ID in case of renting a sports bike(600cc).</p>
                <br />
                <p>RENTAL CHARGES: I WILL PAY FOR THE LENGTH OF TIME I RENT THE MOTORCYCLE AT THE RATE SHOWN IN TARIFF. I AM PRIMARILY LIABLE FOR ALL CHARGES ARISING FROM THE TERMS AND CONDITIONS OF THIS AGREEMENT. IN THE EVENT OF DAMAGES I AGREE TO PAY CHARGE OF REPAIRS OF THE MOTORCYCLES.</p>
                <br />
                <p>CANCELLATION POLICY: IF A CONFIRMED BOOKING IS CANCELLED, I UNDERSTAND AND ACCEPT THAT THE REFUND WOULD BE MADE AS PER THE FOLLOWING SCHEDULE (A) LESS THAN 24 HOURS BEFORE THE SCHEDULED TIME OF HIRE-- NO REFUND* (B) 24 HOURS TO ONE WEEK BEFORE THE SCHEDULED TIME OF HIRE -- 70% REFUND. (C) MORE THAN ONE WEEK BEFORE THE SCHEDULED DATE OF HIRE -- 90% REFUND. (D) SNAPWHEELS CANCELS THE BOOKING DUE TO BREAK DOWN, NON-AVAILABILITY OF THE BIKE OR ANY OTHER UNFORESEEN REASON - 100% REFUND.</p>
                <br />
                <p>NO SHOW: SNAPWHEELS WILL NOT BE LIABLE FOR ANY REFUND IF I DON’T PICK UP THE RESERVED VECHILE WITHIN THE DURATION FOR WHICH THE VEHICLE HAS BEEN RESERVED.</p>
                <br />
                <p>FUEL CHARGES: TARRIF SCHEDULE DOES NOT COVER COST OF FUEL AND I SHALL REFUEL IT AT MY OWN COST. I WILL PAY A FUEL SERVICE CHARGE IF I RETURN THE VEHICLE WITH LESS FUEL THAN WHEN RENTED.</p>
                <br />
                <p>OVERTIME : IF I DON’T RETURN THE VEHICLE BEFORE THE END OF RESERVATION PERIOD, I WILL PAY AN OVERTIME CHARGE WHICH WILL BE DOUBLE OF TARIFF RATE PER HOUR FOR EACH EXTRA HOUR BEYOND THE RESERVATION PERIOD. IN CASE THE VEHICLE IS NOT RETURNED WITHIN THE BUSINESS DAY (9 AM- PM),
                     THE RETURN CAN HAPPEN ONLY THE NEXT DAY AND OVERTIME CHARGES WILL APPLY ACCORDINGLY. 
                     I AGREE TO PAY SNAPWHEELS ALL OF THE FOLLOWING CHARGES THAT MAY COME DUE; (A) ALL FINES, PENALTIES, FORFEITURES, COURT COSTS AND OTHER EXPENSES (INCLUDING FINE FOR PARKING IN NO PARKING, TRAFFIC AND VIOLATIONS);
                      (B) UNLESS THE VEHICLE IS STOLEN OR DESTROYED, IF I DO NOT RETURN THE MOTORCYCLE TO SNAPWHEELS ON THE DATE AND TIME SPECIFIED ABOVE, ;
                       (C) IF I AM IN DEFAULT UNDER THIS AGREEMENT SNAPWHEELS MAY RETAIN THE SECURITY DEPOSIT AND OTHER FUNDS PAID BY ME TO SNAPWHEELS, AND I WILL BE LIABLE FOR ANY AND ALL ADDITIONAL DAMAGES TO SNAPWHEELS.</p>
                       <br />
                <p>RETURN OF THE MOTORCYCLE: I WILL RETURN THE MOTORCYCLE ON THE DATE AND TIME INDICATED ABOVE, IN THE SAME CONDITION AS WHEN RECEIVED, ONLY ORDINARY WEAR AND TEAR FROM PROPER USE EXCEPTED. I WILL RETURN THE MOTORCYCLE SOONER UPON SNAPWHEELS DEMAND. ANY MOTORCYCLE NOT RETURNED WITHIN FOUR HOURS OF THE RETURN TIME SPECIFIED ABOVE WILL BE REPORTED TO THE POLICE AS STOLEN. I WAIVE ALL CLAIMS AGAINST SNAPWHEELS FOR ANY CONSEQUENCES ENSUING FROM SNAPWHEELS MAKING SUCH REPORT. FAILURE TO RETURN THE MOTORCYCLE MAY CONSTITUTE A FELONY PUNISHABLE BY LAW.</p>.
                <br />
                <p>DAMAGE / LOSS OF MOTORCYCLE: IF THE MOTORCYCLE IS STOLEN OR DAMAGED IRRESPECTIVE OF MY NEGLIGENCE OR INTENTIONAL MISCONDUCT, I WILL PAY TO SNAPWHEELS (A) ITS RETAIL FAIR MARKET VALUE BEFORE THEFT OR DAMAGE, UNLESS SNAPWHEELS REPAIR COST PLUS THE REDUCTION OF THE MOTORCYCLES VALUE AFTER REPAIRS IS LESS AND SNAPWHEELS ARE NOT REQUIRED BY LAW TO SALVAGE THE MOTORCYCLE, IN WHICH CASE I WILL PAY THE LATTER AMOUNT; (B) LOSS OF USE BASED ON REASONABLE DOWNTIME, OR AS SPECIFIED BY LAW (EXCEPT FOR THEFT, WHERE THE MOTORCYCLE IS NOT COVERED), (C) DIMINUTION OF VALUE, LOSS OF USE, AND ADMINISTRATIVE FEES.</p>
                <br />
                <p>I AGREE THAT SNAPWHEELS WILL NOT BE LIABLE TO ME FOR ANY LOSS, CONSEQUENTIAL OR OTHER DAMAGES OR EXPENSES OF ANY KIND CAUSED DIRECTLY OR INDIRECTLY BY, OR ARISING IN CONNECTION WITH, THE MOTORCYCLE, ITS USE, OR OPERATION OR FAILURE TO OPERATE, MAINTENANCE OR FAILURE TO BE MAINTAINED, OR BY ANY INTERRUPTION OF SERVICE OR LOSS OF USE OF THE MOTORCYCLE.</p>
                <br />
                <p>PROHIBITED USES: I WILL NOT USE OR PERMIT THE MOTORCYCLE TO BE USED (A) BY ANY PERSON OTHER THAN ME; (B) TO CARRY PASSENGERS OR PROPERTY FOR HIRE; (C) TO TOW, OR TO BE TOWED; (D) TO BE OPERATED ON AN UNPAVED ROAD; (E) TO BE OPERATED IN A RACE OR CONTEST; (F) TO INSTRUCT AN UNLICENSED PERSON IN THE OPERATION OF THE MOTORCYCLE; (G) TO BE OPERATED BY ANY PERSON WHO IS PROHIBITED BY LAW FROM OPERATING A MOTOR VEHICLE; (H) WHILE UNDER THE INFLUENCE OF ALCOHOL OR ANY CONTROLLED SUBSTANCE, OR A PRESCRIPTION OR NONPRESCRIPTION DRUG WHICH COULD IMPAIR MY ABILITY TO OPERATE THE MOTORCYCLE; (I) FOR AN ILLEGAL PURPOSE, INCLUDING TRANSPORTATION OF A CONTROLLED SUBSTANCE OR CONTRABAND. A VIOLATION OF THIS PARAGRAPH AUTOMATICALLY TERMINATES THIS AGREEMENT AND MAKES ME LIABLE TO SNAPWHEELS FOR ALL FINES, FORFEITURES, LIENS AND RECOVERY AND STORAGE COSTS, INCLUDING ALL RELATED LEGAL EXPENSES.</p>
                <br />
                <p>NO ASSIGNMENT: I WILL NOT SELL, TRANSFER, ASSIGN OR SUBLEASE ANY OF MY INTEREST IN THIS AGREEMENT OR THE MOTORCYCLE AND ANY SUCH ATTEMPTED SALE, ASSIGNMENT TRANSFER OR SUBLEASE IS VOID AND OF NO EFFECT.</p>
                <br />
                <p>PERSONAL INFORMATION: I UNDERSTAND THAT THE PERSONAL INFORMATION I HAVE DISCLOSED IN THIS AGREEMENT WILL BE COLLECTED AND STORED BY SNAPWHEELS AND SNAPWHEELS AFFILIATES FOR THE PURPOSES OF SUPPLYING A RECORD OF MY RENTAL. BY SIGNING THIS AGREEMENT I AUTHORIZE SNAPWHEELS TO PROCESS MY INFORMATION AND DISCLOSE IT TO SNAPWHEELS AFFILIATES, AND I ALSO AUTHORIZE SNAPWHEELS TO USE MY PERSONAL INFORMATION FOR VARIOUS PURPOSES, INCLUDING DIRECT MARKETING ACTIVITIES. I UNDERSTAND THAT I HAVE THE RIGHT TO STOP THE PROCESSING OF MY PERSONAL INFORMATION BY SENDING SNAPWHEELS A WRITTEN REQUEST TO THAT EFFECT.</p>
                <br />
                <p>OTHERS: SNAPWHEELS is an aggregator that connects the vendor and the user. In case of any dispute, it should be resolved between the vendor and the user. The vehicles and other suppliers providing travel or other services for SNAPWHEELS are independent contractors and not agents or employees of SNAPWHEELS are not liable for the acts, errors, omissions, representations, warranties, breaches or negligence of any such suppliers or for any personal injuries, death, property damage, or other damages or expenses resulting therefrom. SNAPWHEELS has no liability and will make no refund in the event of any delay, cancellation, overbooking, strike, force majeure or other causes beyond their direct control, and they have no responsibility for any additional expense, omissions, delays, re-routing or acts of any government or authority. The security deposit will be refunded only after checking the damages and if any damage is found, it will be deducted from the deposit.</p>


                <h5>Changes to These Terms and Conditions</h5>
                <p>We reserve the right, at Our sole discretion, to modify or replace these Terms at any time. If a revision is material We will make reasonable efforts to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at Our sole discretion.</p>
                <p>By continuing to access or use Our Service after those revisions become effective, You agree to be bound by the revised terms. If You do not agree to the new terms, in whole or in part, please stop using the website and the Service.</p>
                <h5>Contact Us</h5>
                <p>If you have any questions about these Terms and Conditions, You can contact us:</p>
                <p>By email: support@smartsol.in</p>
                <p>By visiting this page on our website: <a href="https://www.socialcard.in/support" rel="external nofollow noopener" target="_blank">https://www.socialcard.in/support</a></p>
                <br />
                <br />
                
            </div>
        )
    }
}